import { PageHeader } from '../components/Layout.tsx';

const phases = [
  { number: '01', title: 'Evidence foundation', status: 'NOW', copy: 'Build trustworthy labels before training tactical judgment.', items: ['Immutable source video + exact frame timestamps', 'Phrase starts, halts, no-touch outcomes, and score deltas', 'Left/right identities, piste calibration, lights, and referee signals', 'Two-pass human review with uncertainty and rule citations'] },
  { number: '02', title: 'Perception assistance', status: 'NEXT', copy: 'Let models propose geometry while humans correct it.', items: ['Fencer segmentation and persistent left/right tracks', 'Body + weapon keypoints with occlusion flags', 'Piste homography and real-world distance estimates', 'Active learning: surface the lowest-confidence frames'] },
  { number: '03', title: 'Temporal actions', status: 'TRAIN', copy: 'Learn what happens and when, without making calls yet.', items: ['Play/Halt and phrase boundary proposals', 'Footwork, arm-extension, blade-contact, and hit events', 'Ordered event graph with uncertainty intervals', 'Per-action precision/recall and cross-tournament splits'] },
  { number: '04', title: 'Rule-constrained calls', status: 'LATER', copy: 'Combine observed evidence with a deterministic sabre rules layer.', items: ['Priority transition graph, not free-form guesswork', 'Retrieve versioned FIE/USA passages for each proposal', 'Abstain when timing uncertainty can change the call', 'Human adjudication remains ground truth'] },
];

export function RoadmapPage() {
  return <div className="page roadmap-page"><PageHeader eyebrow="HUMAN → ASSISTED → AUTOMATED" title="Model roadmap"><p>Ship useful assistance at every stage; earn the right to automate the call.</p></PageHeader>
    <div className="roadmap-line">{phases.map((phase, index) => <article key={phase.number} className={index === 0 ? 'current' : ''}><div className="roadmap-marker"><span>{phase.number}</span></div><header><small>{phase.status}</small><h2>{phase.title}</h2><p>{phase.copy}</p></header><ul>{phase.items.map((item) => <li key={item}><span>✓</span>{item}</li>)}</ul></article>)}</div>
    <section className="model-stack"><div><p className="eyebrow">REFERENCE MODEL STACK</p><h2>One pipeline, measurable stages</h2><p>Each output can be corrected independently and evaluated before it feeds the next stage.</p></div><div className="stack-flow"><span>Video<br /><small>FFmpeg / PTS</small></span><i>→</i><span>Geometry<br /><small>RTMPose + SAM 2</small></span><i>→</i><span>Tracking<br /><small>CoTracker + IDs</small></span><i>→</i><span>Actions<br /><small>BiFenceNet TCN + VideoMAE</small></span><i>→</i><span>Call<br /><small>Event graph + rules</small></span></div></section>
    <section className="quality-gates"><p className="eyebrow">GO / NO-GO GATES</p><div><article><strong>≥ 0.95</strong><span>Phrase-boundary F1 before auto-segmentation defaults on</span></article><article><strong>≥ 0.90</strong><span>Left/right track accuracy across camera cuts</span></article><article><strong>&lt; 2f</strong><span>Median event-onset error at normalized 60 fps</span></article><article><strong>100%</strong><span>Calls carry evidence, ruleset, confidence, and abstention path</span></article></div></section>
  </div>;
}
